#############################################################################
# Makefile for building: myCom
# Generated by qmake (2.01a) (Qt 4.7.0) on: Tue Jun 25 19:26:52 2013
# Project:  myCom.pro
# Template: app
# Command: /home/sufeng/qtsdk-2010.05/qt/bin/qmake -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile myCom.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SQL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../../qtsdk-2010.05/qt/mkspecs/linux-g++ -I. -I../../qtsdk-2010.05/qt/include/QtCore -I../../qtsdk-2010.05/qt/include/QtNetwork -I../../qtsdk-2010.05/qt/include/QtGui -I../../qtsdk-2010.05/qt/include/QtSql -I../../qtsdk-2010.05/qt/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/sufeng/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/home/sufeng/qtsdk-2010.05/qt/lib -lQtSql -L/home/sufeng/qtsdk-2010.05/qt/lib -lQtGui -L/usr/X11R6/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/sufeng/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		qextserialbase.cpp \
		posix_qextserialport.cpp \
		myinputpanel.cpp \
		myinputpanelcontext.cpp \
		videodevice.cpp moc_widget.cpp \
		moc_qextserialbase.cpp \
		moc_myinputpanel.cpp \
		moc_myinputpanelcontext.cpp \
		moc_videodevice.cpp
OBJECTS       = main.o \
		widget.o \
		qextserialbase.o \
		posix_qextserialport.o \
		myinputpanel.o \
		myinputpanelcontext.o \
		videodevice.o \
		moc_widget.o \
		moc_qextserialbase.o \
		moc_myinputpanel.o \
		moc_myinputpanelcontext.o \
		moc_videodevice.o
DIST          = ../../qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		myCom.pro
QMAKE_TARGET  = myCom
DESTDIR       = 
TARGET        = myCom

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h ui_myinputpanelform.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: myCom.pro  ../../qtsdk-2010.05/qt/mkspecs/linux-g++/qmake.conf ../../qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		../../qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		../../qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/home/sufeng/qtsdk-2010.05/qt/lib/libQtSql.prl \
		/home/sufeng/qtsdk-2010.05/qt/lib/libQtCore.prl \
		/home/sufeng/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/home/sufeng/qtsdk-2010.05/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile myCom.pro
../../qtsdk-2010.05/qt/mkspecs/common/g++.conf:
../../qtsdk-2010.05/qt/mkspecs/common/unix.conf:
../../qtsdk-2010.05/qt/mkspecs/common/linux.conf:
../../qtsdk-2010.05/qt/mkspecs/qconfig.pri:
../../qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
../../qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
../../qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
../../qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
../../qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
../../qtsdk-2010.05/qt/mkspecs/features/debug.prf:
../../qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
../../qtsdk-2010.05/qt/mkspecs/features/warn_on.prf:
../../qtsdk-2010.05/qt/mkspecs/features/qt.prf:
../../qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
../../qtsdk-2010.05/qt/mkspecs/features/moc.prf:
../../qtsdk-2010.05/qt/mkspecs/features/resources.prf:
../../qtsdk-2010.05/qt/mkspecs/features/uic.prf:
../../qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
../../qtsdk-2010.05/qt/mkspecs/features/lex.prf:
../../qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/home/sufeng/qtsdk-2010.05/qt/lib/libQtSql.prl:
/home/sufeng/qtsdk-2010.05/qt/lib/libQtCore.prl:
/home/sufeng/qtsdk-2010.05/qt/lib/libQtGui.prl:
/home/sufeng/qtsdk-2010.05/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../../qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile myCom.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/myCom1.0.0 || $(MKDIR) .tmp/myCom1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/myCom1.0.0/ && $(COPY_FILE) --parents widget.h qextserialbase.h posix_qextserialport.h myinputpanel.h myinputpanelcontext.h videodevice.h .tmp/myCom1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp qextserialbase.cpp posix_qextserialport.cpp myinputpanel.cpp myinputpanelcontext.cpp videodevice.cpp .tmp/myCom1.0.0/ && $(COPY_FILE) --parents widget.ui myinputpanelform.ui .tmp/myCom1.0.0/ && (cd `dirname .tmp/myCom1.0.0` && $(TAR) myCom1.0.0.tar myCom1.0.0 && $(COMPRESS) myCom1.0.0.tar) && $(MOVE) `dirname .tmp/myCom1.0.0`/myCom1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/myCom1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_qextserialbase.cpp moc_myinputpanel.cpp moc_myinputpanelcontext.cpp moc_videodevice.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_qextserialbase.cpp moc_myinputpanel.cpp moc_myinputpanelcontext.cpp moc_videodevice.cpp
moc_widget.cpp: posix_qextserialport.h \
		qextserialbase.h \
		widget.h
	/home/sufeng/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_qextserialbase.cpp: qextserialbase.h
	/home/sufeng/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) qextserialbase.h -o moc_qextserialbase.cpp

moc_myinputpanel.cpp: ui_myinputpanelform.h \
		myinputpanel.h
	/home/sufeng/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) myinputpanel.h -o moc_myinputpanel.cpp

moc_myinputpanelcontext.cpp: myinputpanel.h \
		ui_myinputpanelform.h \
		myinputpanelcontext.h
	/home/sufeng/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) myinputpanelcontext.h -o moc_myinputpanelcontext.cpp

moc_videodevice.cpp: videodevice.h
	/home/sufeng/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) videodevice.h -o moc_videodevice.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h ui_myinputpanelform.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h ui_myinputpanelform.h
ui_widget.h: widget.ui
	/home/sufeng/qtsdk-2010.05/qt/bin/uic widget.ui -o ui_widget.h

ui_myinputpanelform.h: myinputpanelform.ui
	/home/sufeng/qtsdk-2010.05/qt/bin/uic myinputpanelform.ui -o ui_myinputpanelform.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp myinputpanelcontext.h \
		myinputpanel.h \
		ui_myinputpanelform.h \
		widget.h \
		posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		posix_qextserialport.h \
		qextserialbase.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

qextserialbase.o: qextserialbase.cpp qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialbase.o qextserialbase.cpp

posix_qextserialport.o: posix_qextserialport.cpp posix_qextserialport.h \
		qextserialbase.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o posix_qextserialport.o posix_qextserialport.cpp

myinputpanel.o: myinputpanel.cpp myinputpanel.h \
		ui_myinputpanelform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myinputpanel.o myinputpanel.cpp

myinputpanelcontext.o: myinputpanelcontext.cpp myinputpanelcontext.h \
		myinputpanel.h \
		ui_myinputpanelform.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myinputpanelcontext.o myinputpanelcontext.cpp

videodevice.o: videodevice.cpp videodevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videodevice.o videodevice.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_qextserialbase.o: moc_qextserialbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qextserialbase.o moc_qextserialbase.cpp

moc_myinputpanel.o: moc_myinputpanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myinputpanel.o moc_myinputpanel.cpp

moc_myinputpanelcontext.o: moc_myinputpanelcontext.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myinputpanelcontext.o moc_myinputpanelcontext.cpp

moc_videodevice.o: moc_videodevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videodevice.o moc_videodevice.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

